#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Amazon Braket PennyLane Plugin documentation build configuration file,
# created by sphinx-quickstart on Tue Apr 17 11:43:51 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import re
import sys
from pathlib import Path

from pennylane_sphinx_theme import templates_dir
from sphinx.application import Sphinx

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("_ext"))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(".")), "doc"))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = "1.6"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx.ext.inheritance_diagram",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinx_automodapi.automodapi",
]

autosummary_generate = True
autosummary_imported_members = False
automodapi_toctreedirnm = "code/api"
automodsumm_inherited_members = True
numpydoc_show_class_members = False

# Add any paths that contain templates here, relative to this directory.

templates_path = [templates_dir()]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "Amazon Braket PennyLane Plugin"
copyright = "Amazon.com, Inc. or its affiliates. All Rights Reserved."
author = "Amazon"

add_module_names = False

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

# The full version, including alpha/beta/rc tags.
with open("../src/braket/pennylane_plugin/_version.py") as f:
    release = f.readlines()[-1].split()[-1].strip("\"'")

# The short X.Y version.
version = re.match(r"^(\d+\.\d+)", release).expand(r"\1")

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# today_fmt is used as the format for a strftime call.
today_fmt = "%Y-%m-%d"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
show_authors = True

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------


# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = None

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = "_static/favicon.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
# html_sidebars = {
#    '**': [
#        'about.html',
#        'navigation.html',
#        'relations.html',  # needs 'show_related': True theme option to display
#        'searchbox.html',
#        'donate.html',
#    ]
# }

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'h', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'r', 'sv', 'tr'
# html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
# html_search_scorer = 'scorer.js'

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "AmazonBraketPennyLanePlugindoc"

# # -- Xanadu theme ---------------------------------------------------------
html_theme = "pennylane"
html_theme_path = ["."]

# Register the theme as an extension to generate a sitemap.xml
# extensions.append("guzzle_sphinx_theme")

# xanadu theme options (see theme.conf for more information)
html_theme_options = {
    "navbar_name": "PennyLane-Braket",
    "toc_overview": True,
    "navbar_active_link": 3,
    "google_analytics_tracking_id": "G-C480Z9JL0D",
}

edit_on_github_project = "aws/amazon-braket-pennylane-plugin-python"
edit_on_github_branch = "main/doc"

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

latex_additional_files = ["macros.tex"]

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "Amazon Braket PennyLane Plugin.tex",
        "Amazon Braket PennyLane Plugin Documentation",
        "Amazon.com Inc.",
        "manual",
    ),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (
        master_doc,
        "Amazon Braket PennyLane Plugin",
        "Amazon Braket PennyLane Plugin Documentation",
        [author],
        1,
    )
]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "Amazon Braket PennyLane Plugin",
        "Amazon Braket PennyLane Plugin Documentation",
        author,
        "Amazon Braket PennyLane Plugin",
        "Plugin for the PennyLane quantum machine learning library.",
        "Miscellaneous",
    ),
]


# ============================================================

# the order in which autodoc lists the documented members
autodoc_member_order = "bysource"

# inheritance_diagram graphviz attributes
inheritance_node_attrs = dict(color="lightskyblue1", style="filled")

# autodoc_default_flags = ['members']
autosummary_generate = True

LLMS_TXT_TITLE = "PennyLane-Braket Plugin"
LLMS_TXT_SUMMARY = (
    "Plugin that gives PennyLane access to the quantum computing devices and "
    "simulators of Amazon Braket, for optimization and automatic differentiation of "
    "hybrid quantum-classical computations."
)
LLMS_TXT_BASE_URL = "https://amazon-braket-pennylane-plugin-python.readthedocs.io/en/stable/"
LLMS_TXT_SECTIONS: dict[str, tuple[str, ...]] = {
    "Docs": (),
    "Devices": ("devices/",),
    "API Reference": ("code",),
}


def _llms_txt_section(docname: str) -> str:
    """Return the llms.txt section heading a document belongs under.

    Sections are tried in declaration order, so the first matching prefix wins.
    A document that matches no prefix goes under the first section.
    """
    for heading, prefixes in LLMS_TXT_SECTIONS.items():
        if any(docname.startswith(prefix) for prefix in prefixes):
            return heading
    default_heading, _ = next(iter(LLMS_TXT_SECTIONS.items()))
    return default_heading


def _write_llms_txt(app: Sphinx, exception: Exception | None) -> None:
    """Write llms.txt, a manifest of every built page for LLM discoverability.

    The format follows https://llmstxt.org: an H1 name, a blockquote summary, then
    one file list per H2 section. Pages are grouped so that an agent can tell
    narrative docs, device guides and generated API reference apart.
    """
    if exception or app.builder.name != "html":
        return

    # Read the Docs passes the canonical URL to every build automatically, so this
    # is set in any RTD build and the default only applies elsewhere. See
    # https://docs.readthedocs.com/platform/stable/canonical-urls.html#how-to-specify-the-canonical-url
    base_url = os.environ.get("READTHEDOCS_CANONICAL_URL", LLMS_TXT_BASE_URL)
    if base_url and not base_url.endswith("/"):
        base_url += "/"

    env = app.env
    sections: dict[str, list[str]] = {heading: [] for heading in LLMS_TXT_SECTIONS}
    for docname in sorted(env.all_docs):
        url = f"{base_url}{app.builder.get_target_uri(docname)}"
        sections[_llms_txt_section(docname)].append(f"- [{env.titles[docname].astext()}]({url})")

    lines = [f"# {LLMS_TXT_TITLE}", "", f"> {LLMS_TXT_SUMMARY}"]
    for heading in LLMS_TXT_SECTIONS:
        if sections[heading]:
            lines += ["", f"## {heading}", "", *sections[heading]]

    out = Path(app.outdir) / "llms.txt"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"--> Wrote {out.name}")


def setup(app: Sphinx) -> None:
    """Register build hooks."""
    app.connect("build-finished", _write_llms_txt)
