# Copyright 2019-2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.

import json
from unittest import mock
from unittest.mock import Mock, patch

import numpy as np
import pennylane as qml
import pytest
from braket.aws import AwsQpuArns, AwsQuantumSimulatorArns, AwsQuantumTask
from braket.circuits import Circuit
from braket.tasks import GateModelQuantumTaskResult
from pennylane_braket import AWSIonQDevice, AWSRigettiDevice, AWSSimulatorDevice

SHOTS = 10000
RESULT = GateModelQuantumTaskResult.from_string(
    json.dumps(
        {
            "Measurements": [[0, 0], [1, 1], [1, 1], [1, 1]],
            "MeasuredQubits": [0, 1],
            "TaskMetadata": {
                "Id": "UUID_blah_1",
                "Status": "COMPLETED",
                "Ir": "{}",
                "Shots": SHOTS
            },
        }
    )
)
TASK = Mock()
TASK.result.return_value = RESULT
BELL_STATE = Circuit().h(0).cnot(0, 1)


def test_reset():
    """ Tests that the members of the device are cleared on reset.
    """
    dev = AWSSimulatorDevice(
        wires=2,
        s3_destination_folder=("foo", "bar"),
        shots=SHOTS,
    )
    dev._circuit = BELL_STATE
    dev._task = TASK

    dev.reset()
    assert dev.circuit is None
    assert dev.task is None


def test_apply():
    """ Tests that the device's circuit member is set after apply is called.
    """
    dev = AWSSimulatorDevice(
        wires=2,
        s3_destination_folder=("foo", "bar"),
        shots=SHOTS,
    )
    operations = [qml.Hadamard(wires=0), qml.CNOT(wires=[0, 1]), qml.RX(np.pi/2, wires=1)]
    rotations = [qml.RY(np.pi, wires=0)]
    dev.apply(operations, rotations)

    assert dev.circuit == Circuit().h(0).cnot(0, 1).rx(1, np.pi/2).ry(0, np.pi)


def test_apply_unused_qubits():
    """ Tests that the correct circuit is created when not all qires in the dievce are used.
    """
    dev = AWSSimulatorDevice(
        wires=4,
        s3_destination_folder=("foo", "bar"),
        shots=SHOTS,
    )
    operations = [qml.Hadamard(wires=1), qml.CNOT(wires=[1, 2]), qml.RX(np.pi/2, wires=2)]
    rotations = [qml.RY(np.pi, wires=1)]
    dev.apply(operations, rotations)

    assert dev.circuit == Circuit().h(1).cnot(1, 2).rx(2, np.pi/2).ry(1, np.pi).i(0).i(3)


@pytest.mark.xfail(raises=NotImplementedError)
def test_apply_unsupported():
    """ Tests that apply() throws NotImplementedError when it encounters an unknown gate.
    """
    dev = AWSSimulatorDevice(
        wires=2,
        s3_destination_folder=("foo", "bar"),
        shots=SHOTS,
    )
    mock_op = Mock()
    mock_op.name = "foo"

    operations = [qml.Hadamard(wires=0), qml.CNOT(wires=[0, 1]), mock_op]
    dev.apply(operations)


# The next five tests ensure that for all of the Braket devices, the samples
# generated by generate_samples match those in the results
# and AwsQuantumTask.create is called with the right arguments.

@patch.object(AwsQuantumTask, "create")
def test_generate_samples_ionq(mock_create):
    mock_create.return_value = TASK
    dev = AWSIonQDevice(
        wires=2,
        s3_destination_folder=("foo", "bar"),
        shots=SHOTS,
    )
    dev.apply([qml.Hadamard(wires=0), qml.CNOT(wires=[0, 1])])

    assert (dev.generate_samples() == RESULT.measurements).all()
    assert dev.task == TASK
    mock_create.assert_called_with(
        mock.ANY,
        AwsQpuArns.IONQ,
        BELL_STATE,
        ("foo", "bar"),
        SHOTS,
        poll_timeout_seconds=86400
    )


@patch.object(AwsQuantumTask, "create")
def test_generate_samples_rigetti(mock_create):
    mock_create.return_value = TASK

    dev = AWSRigettiDevice(
        wires=2,
        s3_destination_folder=("foo", "bar"),
        shots=SHOTS,
    )
    dev.apply([qml.Hadamard(wires=0), qml.CNOT(wires=[0, 1])])

    assert (dev.generate_samples() == RESULT.measurements).all()
    assert dev.task == TASK
    mock_create.assert_called_with(
        mock.ANY,
        AwsQpuArns.RIGETTI,
        BELL_STATE,
        ("foo", "bar"),
        SHOTS,
        poll_timeout_seconds=86400
    )


@patch.object(AwsQuantumTask, "create")
def test_generate_samples_qs1(mock_create):
    mock_create.return_value = TASK

    dev = AWSSimulatorDevice(
        wires=2,
        s3_destination_folder=("foo", "bar"),
        shots=SHOTS,
        arn="QS1"
    )
    dev.apply([qml.Hadamard(wires=0), qml.CNOT(wires=[0, 1])])

    assert (dev.generate_samples() == RESULT.measurements).all()
    assert dev.task == TASK
    mock_create.assert_called_with(
        mock.ANY,
        AwsQuantumSimulatorArns.QS1,
        BELL_STATE,
        ("foo", "bar"),
        SHOTS,
        poll_timeout_seconds=120
    )


def test_probability():
    """ Tests that the right probabilities are passed into marginal_prob.
    """
    dev = AWSSimulatorDevice(
        wires=2,
        s3_destination_folder=("foo", "bar"),
        shots=SHOTS,
    )
    dev._task = TASK
    probs = np.array([0.25, 0, 0, 0.75])
    assert (dev.probability() == dev.marginal_prob(probs)).all()
