# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
      - feature/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Maximize build space
      shell: bash
      run: | 
        df -h
        if [ "$RUNNER_OS" != "Windows" ]; then
          sudo rm -rf /usr/share/dotnet & 
          sudo rm -rf /usr/local/lib/android &
          sudo rm -rf /opt/ghc & 
          sudo rm -rf /usr/local/share/boost
        fi
        df -h
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[test]
    - name: Check build space
      shell: bash
      run: | 
        df -h
    - name: Run unit tests
      run: |
        tox -e unit-tests
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      if: ${{ strategy.job-index }} == 0
